name: Build application

on: [push, pull_request]

jobs:
  ubuntu-gcc-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install g++-9
        sudo apt-get install cppcheck
        sudo apt-get install mpich libmpich-dev
        sudo apt-get install libomp-9-dev libtbb-dev
        sudo apt-get install python3-pip
        sudo python3 -m pip install --upgrade pip
        sudo python3 -m pip install setuptools cpplint
        sudo apt-get install valgrind
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -D USE_SEQ=ON -D USE_OMP=ON -D USE_STD=ON ..
        cmake --build . --config -j4
        cd ..
      env:
        CC: gcc-9
        CXX: g++-9
    - name: Run tests
      run: |
        export OMP_NUM_THREADS=4
        source scripts/run.sh
  ubuntu-clang-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install cppcheck
        sudo apt-get install clang-8 mpich libmpich-dev libomp-9-dev libtbb-dev
        sudo apt-get install python3-pip
        sudo python3 -m pip install --upgrade pip
        sudo python3 -m pip install setuptools cpplint
        sudo apt-get install valgrind
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -D USE_SEQ=ON -D USE_OMP=ON -D USE_STD=ON ..
        cmake --build . --config -j4
        cd ..
      env:
        CC: clang-8
        CXX: clang++-8
    - name: Run tests
      run: |
        export OMP_NUM_THREADS=4
        source scripts/run.sh
  windows-msvc-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Build
      run: |
        set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%
        mkdir build
        cd build && cmake -G "Visual Studio 16 2019" -D USE_SEQ=ON -D USE_OMP=ON -D USE_STD=ON .. && cmake --build .
      shell: cmd
    - name: Run tests
      run: |
        set OMP_NUM_THREADS=4
        scripts/run.bat
